name: Codecov
on:
  push:
    branches: [master]
jobs:
  codecov:
    name: Run codecov on master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          cache: sbt
          distribution: adopt
          java-version: 11
      - uses: sbt/setup-sbt@v1
      - uses: actions/cache@v4
        with:
          path: ~/.cache/coursier
          key: coursier-${{hashFiles('**/*.sbt')}}
          restore-keys: coursier-
      - uses: actions/cache@v4
        with:
          path: ~/.sbt
          key: sbt-${{hashFiles('**/*.sbt')}}-${{hashFiles('project/build.properties')}}
          restore-keys: sbt-
      - name: Generate coverage report
        run: sbt clean coverage test coverageReport
      - uses: codecov/codecov-action@v4
