name: PR checks
on:
  pull_request:
jobs:
  test:
    name: Test using JDK ${{matrix.java}} and Scala ${{matrix.scala}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['8', '11']
        scala:
          - 2.12.19
          - 2.12.20
          - 2.13.15
          - 2.13.16
          - 3.3.4
          - 3.5.2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: ${{matrix.java}}
      - uses: actions/cache@v4
        with:
          path: ~/.ivy2/cache
          key: ivy-${{hashFiles('**/*.sbt')}}-${{matrix.scala}}
          restore-keys: ivy-
      - uses: actions/cache@v4
        with:
          path: ~/.sbt
          key: sbt-${{hashFiles('**/*.sbt')}}-${{hashFiles('project/build.properties')}}-${{matrix.scala}}
          restore-keys: sbt-
      - run: sbt ++${{matrix.scala}}! test
  additional-checks:
    name: Run additional checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 11
      - uses: actions/cache@v4
        with:
          path: ~/.ivy2/cache
          key: ivy-${{hashFiles('**/*.sbt')}}
          restore-keys: ivy-
      - uses: actions/cache@v4
        with:
          path: ~/.sbt
          key: sbt-${{hashFiles('**/*.sbt')}}-${{hashFiles('project/build.properties')}}
          restore-keys: sbt-
      - name: Generate coverage report
        run: sbt clean coverage test coverageReport
      - uses: codecov/codecov-action@v4
      - name: Run Scalafix check
        run: sbt fixCheck
      - name: Check formatting
        run: sbt scalafmtCheckAll
      - name: Run Scapegoat
        run: |
          sbt 'set version := "99.0-SNAPSHOT"; publishLocal'
          sbt -Dadd-scapegoat-plugin=true 'set name := "scapegoat-test"; set scapegoatVersion in ThisBuild := "99.0-SNAPSHOT"; scapegoat'
